---
# code: language=ansible
- ansible.builtin.import_tasks: dist_vars.yml

- ansible.builtin.import_tasks: validate_config.yml

- ansible.builtin.include_tasks: setup_repo.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.import_tasks: install.yml
  when: ansible_os_family == 'Debian'

- name: Configure encryption
  when:
    - config.client.encrypt is defined
    - config.client.encrypt.enable
  ansible.builtin.include_tasks: encryption.yaml

- name: Add Exclusions
  ansible.builtin.include_tasks: exclude.yaml
  loop: "{{ config.client.exclude }}"
  loop_control:
    loop_var: exclude
  when: config.client.exclude is defined

- name: Debug Config
  ansible.builtin.debug:
    var: config.client

- name: Configure service
  ansible.builtin.include_tasks: service.yaml
