---
# code: language=ansible
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', pbs_variables) }}"

- ansible.builtin.include_tasks: setup_repo.yml
  when: ansible_os_family == 'Debian' and proxmox_backup_repo

- ansible.builtin.include_tasks: install.yml
  when: ansible_os_family == 'Debian' and proxmox_backup_install

- name: Configure Proxmox Backup Client
  when: proxmox_backup_configure
  block:
    - name: Validating Configuration
      ansible.builtin.import_tasks: validate_config.yml

    - name: Configure encryption
      when:
        - config.client.encrypt is defined
        - config.client.encrypt.enable
      ansible.builtin.include_tasks: encryption.yml

    - name: Add Exclusions
      ansible.builtin.include_tasks: exclude.yml
      loop: "{{ config.client.exclude }}"
      loop_control:
        loop_var: exclude
      when: config.client.exclude is defined

    - name: Debug Config
      ansible.builtin.debug:
        var: config.client

- name: Configure service
  ansible.builtin.include_tasks: service.yml
