---
# code: language=ansible
- name: Generate env files
  ansible.builtin.template:
    src: pbs-env.j2
    dest: /etc/pbs-env
    owner: root
    group: root
    mode: "0600"

- name: Setup Proxmox Backup systemd
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.service }}"
    owner: root
    group: root
    mode: u=rw,g=rw,o=r
    # Cannot validate due to systemd issue
    # validate: systemd-analyze verify %s
  loop:
    - template: service.j2
      service: /etc/systemd/system/proxmox-backup-client.service
    - template: timer.j2
      service: /etc/systemd/system/proxmox-backup-client.timer

- name: Enable and start Proxmox Backup timer
  ansible.builtin.systemd:
    name: "proxmox-backup-client.timer"
    state: started
    enabled: true
    daemon_reload: true
