---
# code: language=ansible
- name: Check required proxmox_backup.server dictionary keys
  ansible.builtin.fail:
    msg: "proxmox_backup.server.{{ required_key }} must be defined"
  when: required_key not in proxmox_backup.server
  with_items: "{{ required_pbs_server_keys }}"
  loop_control:
    loop_var: required_key

- name: Check required proxmox_backup.client dictionary keys
  ansible.builtin.fail:
    msg: "proxmox_backup.client.{{ required_key }} must be defined"
  when: required_key not in proxmox_backup.client
  with_items: "{{ required_pbs_client_keys }}"
  loop_control:
    loop_var: required_key

- name: Check required proxmox_backup.archive dictionary keys
  ansible.builtin.include_tasks: check_archive_keys.yml
  with_items: "{{ proxmox_backup.client.archives }}"
  loop_control:
    loop_var: archive

- name: Check required proxmox_backup.exclude dictionary keys
  ansible.builtin.include_tasks: check_exclude_keys.yml
  with_items: "{{ proxmox_backup.client.exclude }}"
  loop_control:
    loop_var: exclude
  when: proxmox_backup.client.exclude is defined

- name: Merge supplied and default dictionaries
  ansible.builtin.set_fact:
    config: "{{ default_config | combine(proxmox_backup, recursive=true) }}"