galaxy_info:
  name: Proxmox Backup Client
  description: Ansible role for installing and configuring the Proxmox Backup Client
  author: buengese
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: ArchLinux
    - name: Ubuntu
      versions:
        - "focal"
        - "noble"
    - name: Debian
      versions:
        - "buster"
        - "bullseye"
  galaxy_tags:
    - backup
    - proxmox
dependencies: []