---
# code: language=ansible
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-proxmox-backup-client
  vars:
    proxmox_backup:
      server:
        user: backup@pbs
        pass: bla
        host: pbs.example.com
        datastore: bla
      client:
        archives:
          - name: root
            path: /
            format: .pxar